version: '3'
services:
  api:
    container_name: revel-api
    build: ./docker/api
    tty: true
    stdin_open: true
    env_file:
      - ./docker/api/.env
      - ./docker/mysql/.env
    command: revel run api
    ports:
      - 80:9000
      - 443:9000
    volumes:
      - ./api:/go/src/api
      - ./xo:/go/src/xo
    links:
      - mysql
      - redis

  mysql:
    container_name: revel-mysql
    build: ./docker/mysql
    env_file:
      - ./docker/mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
 
  redis:
      container_name: revel-redis
      image: redis:5.0
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      environment: 
        REDIS_PASSWORD: "password"
      volumes:
        - ./docker/redis/data:/data