FROM mysql:5.7.25

# RUN { \
#     echo '[mysqld]'; \
#     echo 'character-set-server=utf8mb4'; \
#     echo 'collation-server=utf8mb4_general_ci'; \
#     echo 'explicit_defaults_for_timestamp = 1'; \
#     echo '[client]'; \
#     echo 'default-character-set=utf8mb4'; \
#     } > /etc/mysql/conf.d/charset.cnf
